from __future__ import annotations

from typing import Any, Protocol

from domains.registry import GraphId


class DomainGraphStore(Protocol):
    graph_id: GraphId

    def all_nodes(self) -> list[dict[str, Any]]: ...

    def all_edges(self) -> list[dict[str, Any]]: ...

    def add_node(self, node_type: str, payload: dict[str, Any]) -> dict[str, Any]: ...

    def add_edge(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class FederatedGraphStore(Protocol):
    def domain(self, graph_id: GraphId) -> DomainGraphStore: ...

    def add_node(self, node_type: str, payload: dict[str, Any]) -> dict[str, Any]: ...

    def add_edge(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def impacted_products_by_supplier(self, supplier_id: str) -> list[dict[str, Any]]: ...

    def shortest_supply_path(self, from_component_id: str, to_product_id: str) -> list[dict[str, Any]]: ...

    def _all_nodes(self) -> list[dict[str, Any]]: ...

    def _all_edges(self) -> list[dict[str, Any]]: ...
